### PR TITLE
Fix MSRV and check it in CI

### LINKED ISSUE #202: Failure to compile with Rust 1.75
When trying to use the new version with the Rust 1.75 compiler, I get the following error:
```
error[E0658]: use of unstable library feature 'error_in_core'
  --> arbitrary-1.4.0/src/lib.rs:52:6
   |
52 | impl core::error::Error for MaxRecursionReached {}
```

It looks like while `std::error::Error` has been around for a while, its presence in `core` is new as of Rust 1.81

### PR DESCRIPTION
**Pull request by djc**
Fixes #202.

### CODE REVIEW

**Review by Manishearth — APPROVED** [review]

**Comment by Manishearth** [comment]
I'd like to land https://github.com/rust-fuzz/arbitrary/pull/205 before the version bump, but this looks good, thanks!

File: src/lib.rs [hunk 1]
```diff
@@ -49,7 +49,7 @@ impl core::fmt::Display for MaxRecursionReached {
     }
 }
 
-impl core::error::Error for MaxRecursionReached {}
+impl std::error::Error for MaxRecursionReached {}
```
Comment (fitzgen) [inline src/lib.rs:52]: Did this not break no-std builds? Shouldn't this be `cfg(feature = "std")`? I guess the no-std PR didn't add CI and no one caught that in review...

Comment (fitzgen) [reply src/lib.rs:52]: Ah nvm, the nostd PR hasn't landed yet.
