### ISSUE TITLE
Failure to compile with Rust 1.75

### ISSUE THREAD

**Issue by akonradi-signal** [rust-fuzz/arbitrary#202]
When trying to use the new version with the Rust 1.75 compiler, I get the following error:
```
error[E0658]: use of unstable library feature 'error_in_core'
  --> arbitrary-1.4.0/src/lib.rs:52:6
   |
52 | impl core::error::Error for MaxRecursionReached {}
```

It looks like while `std::error::Error` has been around for a while, its presence in `core` is new as of Rust 1.81

**Comment by suikammd** [comment]
Same. Incompatible upgrade, should release major version.

**Comment by akonradi-signal** [comment]
It seems like this was an oversight. Fixing as in #204 and releasing a 1.4.1 seems like the right way to move forward.
